name: business_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/users/user-lg.jpg
    - assets/pistons.png
    - assets/scissors.png
    - assets/technology.png
    - assets/tools.png
    - assets/big/img1.jpg
    - assets/big/img2.jpg
    - assets/big/img3.jpg
    - assets/big/img4.jpg
    - assets/big/img5.jpg
    - assets/big/img6.jpg
  
  fonts:
      - family: Montserrat
        fonts:
          - asset: assets/Montserrat-Regular.ttf

      - family: Quicksand
        fonts:
          - asset: assets/Quicksand-Regular.ttf